### ISSUE TITLE
Misalignment of menu texts

### ISSUE THREAD

**Issue by weslyh** [gladguys/gladtask-ng#146]
**Steps to reproduce**
Sign In at(in, on... idk) GladTask

**What is expected?**

The texts should be aligned with the icons.

**What is actually happening?**

The texts are misaligned with the icons.

**Where it was tested**

Browser: Firefox 52.9.0
OS: Linux

![gladtask](https://user-images.githubusercontent.com/49761254/59927127-2144f400-9412-11e9-8ad5-69d9623ff3bc.png)

**Comment by weslyh** [comment]
Display resolution: 1440x900 pixels (381x238 millimeters)

**Comment by alexandrelc16** [comment]
The problem occurs on old versions from Firefox. Probably a bug with Flexbox rendering.
Issue closed because the Gladtask is not crossbrowser, for now.
